services:
  # 使用替换功能将 'minecraftserver' 换成服务端名或者你想要的容器名
  minecraftserver:
    build:
      context: .
      args:
        - JAVA_VERSION=21 # 指定java版本（目前没用）
      dockerfile: Dockerfile
    container_name: minecraftserver
    stop_grace_period: 30s
    environment:
      - CORE_URL=https://api.papermc.io/v2/projects/paper/versions/1.18.2/builds/388/downloads/paper-1.18.2-388.jar  # 如果存在，自动下载并以该核心启动服务器，或者不填写这个变量，直接从现有服务端核心启动
      - MIN_RAM=8G # 最小分配内存
      - MAX_RAM=8G # 最大分配内存
      - OTHER_ARGS="-XX:+UseZGC -XX:+ZGenerational -XX:+AlwaysPreTouch --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang.reflect=ALL-UNNAMED -Dfile.encoding=UTF-8" # 其他启动参数，java21 zgc优化，java21以下需更换
    restart: unless-stopped
    ports:
      - "<IP:PORT>:25565" # 如0.0.0.0:25565:25565
    volumes: # 根据情况映射文件
      - minecraftserver:/minecraft

# 创建filebrowser，方便修改配置文件、一键下载存档等 默认账户密码均为admin
  filebrowser:
    image: filebrowser/filebrowser:s6
    container_name: filebrowser_minecraftserver
    ports:
      - "<IP:PORT>:80" # 如0.0.0.0:12345:80
    volumes:
      - minecraftserver:/srv
    environment:
      - PUID=0 # 设置权限与组，便于修改文件
      - PGID=0

# 创建卷，用于存储
volumes:
  minecraftserver:

